global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'filehost'
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
    basic_auth:
      username: 'administrador'
      password: '1234'
    static_configs:
      - targets: ['host.docker.internal:8081']
